name: "lekko-setup"
description: >
  Install lekko for use in other jobs.
branding:
  icon: play
  color: purple
inputs:
  version:
    description: The version of lekko to set up.
    required: false
    default: '0.2.32'
  apikey:
    description: Lekko apikey used to access private lekko resources
    required: true # This is required because Lekko's releases are private.
  github_token:
    description: The GitHub token to use when making API requests. Deprecated.
    required: false
runs:
  using: "node16"
  main: "./dist/main.js"
