name: test
on: [push]
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./ # Run the local version of the action.
        with:
          version: 'latest'
          github_token: ${{ secrets.LEKKO_CI_GITHUB_PAT }}
      - run: lekko --version
