name: test
on: [push]
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./ # Run the local version of the action.
        with:
          version: 'v0.2.13'
          github_token: ${{ secrets.PAT }}
      - run: lekko --version
